import { Box, Container } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";
import React from "react";

const Home = () => {
  return (
    <Box>
      <Head>
        <title>大丸白衣 徳島工場</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxW="1000px" mt={6} p={6}>
          <Box>トップぺージ</Box>
          <Link href="/markslip/new">
            <a>
              <Box>マーク伝票作成</Box>
            </a>
          </Link>
        </Container>
      </main>
    </Box>
  );
};

export default Home;
