import { Box, Container, Textarea } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>大丸白衣 徳島工場</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxW="1000px" mt={6} p={6}>
          <Textarea bg="white" />
        </Container>
      </main>
    </Box>
  );
};

export default Home;
