import {
  Box,
  Button,
  Container,
  Flex,
  Input,
  Textarea,
} from "@chakra-ui/react";
import Head from "next/head";
import React, { useState } from "react";

const Marking = () => {
  const [textArea, setTextArea] = useState("");
  const [inputAreaTitle, setInputAreaTitle] = useState("");

  const handleTextArea = (e: any) => {
    setTextArea(e.target.value);
  };

  const handleClick = () => {
    const newArray = textArea.split("\n").map((record) => {
      const field = record.split("   ");
      return field;
    });
    console.log(newArray);
  };
  console.log(inputAreaTitle);
  return (
    <Box>
      <Head>
        <title>大丸白衣 徳島工場</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxW="1000px" mt={6} p={6}>
          <Textarea bg="white" value={textArea} onChange={handleTextArea} />
          <Button onClick={handleClick} colorScheme="teal">
            ボタン
          </Button>
          <Flex>
            <Input
              value={inputAreaTitle}
              onChange={(e) => setInputAreaTitle(e.target.value)}
            />
            <Input />
            <Input />
          </Flex>
        </Container>
      </main>
    </Box>
  );
};

export default Marking;
